import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react';
import { Row, Col, Button, Form, Input, Divider } from 'antd'
import { GameCard } from '../components/game-card'
import apiService from '../services/api.service'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [form] = Form.useForm();
  const [userCards1, setUserCards1] = useState([]);
  const [error1, setError1] = useState(false);
  const [userCards2, setUserCards2] = useState([]);
  const [error2, setError2] = useState(false);
  const [winner, setWinner] = useState(null);

  const error = [error1, error2];
  const userCards = [userCards1, userCards2];

  useEffect(() => {
    if (userCards1.length > 0 && userCards2.length > 0 && !error1 && !error2) {
      if (JSON.stringify(userCards1) === JSON.stringify(userCards2)) {
        setWinner(0);
      } else {
        setWinner(Math.floor(Math.random() * 2) + 1);
      }
    }
  }, [userCards1, userCards2, error1, error2]);

  const handleBattle = () => {
    setWinner(null);
    setError1(false);
    setUserCards1([]);
    setError2(false);
    setUserCards2([]);
    const { email1, email2 } = form.getFieldsValue(true);
    if (email1.trim() === email2.trim()) {
      return alert('Please enter different emails');
    }

    apiService.getUserCards(email1).then(setUserCards1).catch(error => setError1(true));

    apiService.getUserCards(email2).then(setUserCards2).catch(error => setError2(true));
  };

  const handleBuySameCards = async index => {
    const email = form.getFieldValue(`email${index}`);
    const password = form.getFieldValue(`password${index}`);
    const cards = (index === 1 ? userCards2 : userCards1).map(c => ({
      card_id: c.id,
      count: c.count,
    }));

    try {
      await apiService.updateUserCards(email, password, cards);
      (index === 1 ? setUserCards1 : setUserCards2)(index === 1 ? userCards2 : userCards1);
      // setWinner(0);
    } catch (e) {
      alert(e.response.data.message);
    }
  };
  console.log(winner)

  return (
    <div className={styles.container}>
      <Head>
        <title>Game site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Row justify="center">
          <Button type="primary" onClick={handleBattle}>Battle</Button>
        </Row>
        <Form form={form} layout="vertical">
          <Row gutter={25} justify="space-between">
            {[1, 2].map(index => (
              <Col span={8} key={index}>
                <h2>Player {index} {winner === 0 && <b>DRAW</b>} {winner > 0 && (winner === index ? <b>WON</b> : <b>LOST</b>)}</h2>
                <Form.Item
                  name={`email${index}`}
                  initialValue={`name${index}@example.com`}
                  label="Email Address"
                >
                  <Input />
                </Form.Item>
                {winner !== null && winner !== index && (
                  <>
                    <Form.Item name={`password${index}`} initialValue="a12345678" label="Password">
                      <Input.Password />
                    </Form.Item>
                    <Button type="primary" onClick={() => handleBuySameCards(index)}>Buy same cards</Button>
                  </>
                )}
              </Col>
            ))}
          </Row>
        </Form>

        <Divider />
        <Row gutter={25} justify="space-between">
          {[0, 1].map(index => (
            <Col span={11} key={index}>
              {error[index] && (
                <Button href={process.env.NEXT_PUBLIC_MARKET_URL} block>
                  Go to market
                </Button>
              )}
              <Row gutter={25}>
                {userCards[index].map(card => (
                  <Col sm={12} xl={8} xxl={6} key={card.id}>
                    <GameCard {...card} />
                  </Col>
                ))}
              </Row>
            </Col>
          ))}
        </Row>
      </main>

    </div>
  )
}
